ORDER_HEADER = 'Your order please: '
ORDER_EXAMPLE = 'Example order: 10 R12'
ORDER_COMPLETE = 'Type done and enter to calculate.'
ORDER_FORMAT_ERROR = 'Please pay attention to the item code format and qty'
THANK_YOU_MESSAGE = 'Thank you for your order. Calculating now... '
CONTINUE = 'Recorded. Enter your new order or done to calculate: '
DONE = 'done'